export const Game2048ABI = [
  "function buyPlay() external payable",
  "function claimReward(uint256 milestone) external",
  "function getAvailablePlays(address player) external view returns (uint256)",
  "function hasClaimed(address player, uint256 milestone) external view returns (bool)",
  "function getRewardAmount(uint256 milestone) external pure returns (uint256)",
  "function getContractBalance() external view returns (uint256)",
  "function availablePlays(address) external view returns (uint256)",
  "function claimedMilestones(address, uint256) external view returns (bool)",
  "function PLAY_COST() external view returns (uint256)",
  "function REWARD_2048() external view returns (uint256)",
  "function REWARD_4096() external view returns (uint256)",
  "function REWARD_8192() external view returns (uint256)",
  "function MILESTONE_2048() external view returns (uint256)",
  "function MILESTONE_4096() external view returns (uint256)",
  "function MILESTONE_8192() external view returns (uint256)",
  "function owner() external view returns (address)",
  "function withdraw() external",
  "function transferOwnership(address newOwner) external",
  "event PlayBought(address indexed player)",
  "event RewardClaimed(address indexed player, uint256 milestone, uint256 reward)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
];
